### ISSUE TITLE
Label of BelongsTo relationship not shown in nested form component

### ISSUE THREAD

**Issue by BobbyBorisov** [Lupennat/nested-form#8]
Hello! First of all thank you for forking and taking care of nova-nested-form package! 

I am about to upgrade a project from Nova 3 to Nova 4 and currently I am experiencing the issue of label for BelongsTo relationship not being shown on the form page. Attaching screenshot. 

I did a fresh laravel nova project + your package and still experiencing the issue.

I have 3 fields as you can see but the label is not shown. 

<img width="1412" alt="Screenshot 2023-09-12 at 17 04 49" src="https://github.com/Lupennat/nested-form/assets/3647471/b265ccb1-c06a-48b4-b1f2-9d9f57a5a6ba">

**Comment by Lupennat** [comment]
In the next few weeks this repository will be archived and replaced by [nova-nested-many](https://packagist.org/packages/lupennat/nova-nested-many)

I suggest you try to use this new package and see if the bug still exists.
